name: TokenAuthenticationDemo
packages:
  ReactiveAPI:
    url: https://github.com/sky-uk/ReactiveAPI.git
    branch: spm
targets:
  TokenAuthenticationDemo:
    type: application
    platform: iOS
    deploymentTarget: 12.2
    sources: [Sources]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: it.sky.TokenAuthenticationDemo
    dependencies:
      - package: ReactiveAPI

