name: ReactiveAPI
options:
  bundleIdPrefix: it.sky
  deploymentTarget:
    iOS: "13.0"
packages:
  Swifter:
    url: https://github.com/httpswift/swifter.git
    from: 1.5.0
  CombineExt:
    url: https://github.com/CombineCommunity/CombineExt.git
    from: 1.0.0
targets:
  ReactiveAPI:
    templates:
      - iOSFramework
    sources:
      - path: Sources/ReactiveAPI
    scheme:
      testTargets:
        - ReactiveAPI-Tests
  ReactiveAPIExt:
    templates:
      - iOSFramework
    sources:
      - path: Sources/ReactiveAPIExt
    scheme:
      testTargets:
        - ReactiveAPIExt-Tests
  ReactiveAPI-Tests:
    templates:
      - iOSTestFramework
    sources:
      - Tests/ReactiveAPITests
    dependencies:
      - target: ReactiveAPI
  ReactiveAPIExt-Tests:
    templates:
      - iOSTestFramework
    sources:
      - Tests/ReactiveAPIExtTests
    dependencies:
      - target: ReactiveAPIExt
targetTemplates:
  iOSFramework:
    platform: iOS
    type: framework
    info:
      path: ${target_name}.plist
      properties:
        CFBundleIdentifier: it.sky.${target_name}
        CFBundleShortVersionString: "1.13.0"
    sources:
      - path: Sources/ReactiveAPI
    scheme:
      gatherCoverageData: true
  iOSFramework:
    platform: iOS
    type: framework
    info:
      path: ${target_name}.plist
      properties:
        CFBundleIdentifier: it.sky.${target_name}
        CFBundleShortVersionString: "1.13.0"
    sources:
      - path: Sources/ReactiveAPIExt
    scheme:
      gatherCoverageData: true
    dependencies:
      - package: CombineExt
  iOSTestFramework:
    type: bundle.unit-test
    platform: iOS
    scheme: {}
    dependencies:
      - package: Swifter
