# Warning, do not change version.
version: 2.1

jobs:
  prebase:
    macos:
      xcode: 12.0.0
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run:
         name: Build ReactiveAPIDemo
         command: >
           xcodebuild
           -scheme ReactiveAPIDemo
           -destination 'platform=iOS Simulator,name=iPhone 11'

workflows:
  version: 2
  build-test:
    jobs:
      - prebase:
          context:
            - skyita-mobile
